name: CV Integration engine dev CICD pipeline

on:
  push:
    branches:
    - dev
    
jobs:
  call-base-pipe-line:
    uses: ./.github/workflows/cv-integration-engine-ci-cd-pipeline-base.yml
    with:
      integration-env: DEV
