name: Email Sending Test

on:
  workflow_dispatch
    
jobs:
 send-mail:
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1
      
    - name: print notes
      shell: bash
      run: |
       echo "${{ steps.extract-release-notes.outputs.release_notes }}"
       echo "notes printed"
          
    - name: Send mail
      uses: dawidd6/action-send-mail@v3.7.1
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.TEST_EMAIL_USERNAME }}
        password: ${{ secrets.TEST_EMAIL_PASSWORD }}
        subject: ${{ github.job }} job of ${{ github.repository }}
        body: |
          ${{ steps.extract-release-notes.outputs.release_notes }} ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} run id ${{ github.run_id }}.
        to: ${{ vars.TEST_TO_EMAILS }}   # comma-separated string
        from: ${{ vars.TEST_FROM_EMAIL }}
