name: E-Mail Release Notification
# on:
  # release:
    # types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify about a new release
      uses: ba-st-actions/email-release-notification@v3.0.0
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        RECIPIENTS_URL: ${{ vars.RELEASE_NOTES_RECIPIENTS }}
        SENDER_EMAIL: 'xin.li@commercevision.com.au'
        DISTRIBUTION_LISTS: 'xin.li@commercevision.com.au'
