name: Send Release Notificaion

on:
  release:
    types: [created] # created,published
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Notifier Action
      uses: bitoiu/release-notify-action@v3.1.2
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        RECIPIENTS: ${{ vars.RELEASE_NOTES_RECIPIENTS }}
        SENDER_EMAIL: 'porrimaxin@gmail.com'
