name: Send Release Notificaion

# on:
  # release:
    # types: [created] # created,published
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Notifier Action
      uses: xinlibrisbane/release-notify-action@master # bitoiu/release-notify-action@v1.0
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        # BCC_RECIPIENTS_URL: ${{ vars.BCC_RECIPIENTS_URL }}
        RELEASE_NOTES_RECIPIENTS: ${{ vars.RELEASE_NOTES_RECIPIENTS }}
        RELEASE_NOTES_BCC_RECIPIENTS: ${{ vars.RELEASE_NOTES_BCC_RECIPIENTS }}
        SENDER_EMAIL: ${{ vars.SENDER_EMAIL }}
