# name: E-Mail Release Notification
# on:
  # release:
    # types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify about a new release
      uses: ba-st-actions/email-release-notification@v3.1.2
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        RECIPIENTS_URL: ${{ vars.RELEASE_NOTES_RECIPIENTS }}
        SENDER_EMAIL: 'porrimaxin@gmail.com'
        DISTRIBUTION_LISTS: 'porrimaxin@gmail.com'
